# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state-bucket-ma"
    encrypt = true
    key     = "mgmt-account/eu-west-1/s3/terraform.tfstate"
    region  = "eu-west-2"
  }
}
